PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
  "author": "Michael Chan",
  "likes": 8,
  "title": "React patterns",
  "url": "https://reactpatterns.com/",
}
